name = "undangan-app"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-03"

routes = [
  { pattern = "dianrafiyq.site", custom_domain = true }
]

[build]
command = "worker-build --release"