name = "undangan-app"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-03"

routes = [
  { pattern = "dianrafiyq.site", custom_domain = true }
]

[[kv_namespaces]]
binding = "assets"
id = "eebb5dd628ad493fba72a3e9b42242df"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "guest-list"
database_id = "4188cd29-38ac-4c78-8f9d-07288a1a494a"

[build]
command = "worker-build --release"