name = "undangan-app"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-03"

routes = [
  { pattern = "dianrafiyq.site", custom_domain = true }
]

[[kv_namespaces]]
binding = "assets"
id = "eebb5dd628ad493fba72a3e9b42242df"

[build]
command = "worker-build --release"